In [1]:
import pandas as pd

In [2]:
# =====================================================
# Load Dataset & Basic Preprocessing
# =====================================================

df = pd.read_csv('../Data/electricity_demand.csv')
df.head(5)

,datetime,demand_MW,temperature,humidity,wind_speed,pressure,precipitation,holiday,weekend,hour,day_of_week,month,season
0,2021-01-01 00:00:00,3496.9,0.7,73.9,13.8,1004.1,0.2,1,0,0,4,1,Winter
1,2021-01-01 01:00:00,3525.2,0.6,83.1,13.3,1009.2,0.6,1,0,1,4,1,Winter
2,2021-01-01 02:00:00,3290.1,1.0,59.7,9.0,1019.5,1.0,1,0,2,4,1,Winter
3,2021-01-01 03:00:00,3284.3,0.4,57.9,14.9,1013.5,0.0,1,0,3,4,1,Winter
4,2021-01-01 04:00:00,3449.4,2.7,70.9,5.2,1008.2,0.0,1,0,4,4,1,Winter

In [4]:
print("Total Rows In The Dataset:",df.shape[0])
print("Total Columns In The Dataset:",df.shape[1],"\n")

print("Columns Names: ",df.columns,"\n")

print(f"Date Range: {df['datetime'].min()} to {df['datetime'].max()}")

Total Rows In The Dataset: 26280
Total Columns In The Dataset: 13

Columns Names:  Index(['datetime', 'demand_MW', 'temperature', 'humidity', 'wind_speed',
       'pressure', 'precipitation', 'holiday', 'weekend', 'hour',
       'day_of_week', 'month', 'season'],
      dtype='object')

Date Range: 2021-01-01 00:00:00 to 2023-12-31 23:00:00

In [5]:
print("Missing Values In The Dataset:")
print(df.isnull().sum())

Missing Values In The Dataset:
datetime         0
demand_MW        0
temperature      0
humidity         0
wind_speed       0
pressure         0
precipitation    0
holiday          0
weekend          0
hour             0
day_of_week      0
month            0
season           0
dtype: int64

In [6]:
print("Data Info:")
print(df.info())

Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26280 entries, 0 to 26279
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   datetime       26280 non-null  object
 1   demand_MW      26280 non-null  float64
 2   temperature    26280 non-null  float64
 3   humidity       26280 non-null  float64
 4   wind_speed     26280 non-null  float64
 5   pressure       26280 non-null  float64
 6   precipitation  26280 non-null  float64
 7   holiday        26280 non-null  int64
 8   weekend        26280 non-null  int64
 9   hour           26280 non-null  int64
 10  day_of_week    26280 non-null  int64
 11  month          26280 non-null  int64
 12  season         26280 non-null  object
dtypes: float64(6), int64(5), object(2)
memory usage: 2.6+ MB
None

In [7]:
df.describe()

,demand_MW,temperature,humidity,wind_speed,pressure,precipitation,holiday,weekend,hour,day_of_week,month
count,26280.000000,26280.000000,26280.000000,26280.000000,26280.000000,26280.000000,26280.000000,26280.000000,26280.000000,26280.000000,26280.000000
mean,4142.244935,18.833482,64.965396,10.605346,1012.938546,0.600293,0.024658,0.286758,11.500000,3.005479,6.526027
std,1087.756799,10.594626,10.620938,5.528004,8.051965,1.808125,0.155082,0.452256,6.922318,2.000487,3.447917
min,1344.500000,-5.000000,25.100000,0.000000,979.500000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,3449.500000,11.200000,57.600000,6.400000,1007.500000,0.000000,0.000000,0.000000,5.750000,1.000000,4.000000
50%,4016.100000,19.200000,64.900000,9.900000,1013.000000,0.000000,0.000000,0.000000,11.500000,3.000000,7.000000
75%,5052.125000,25.100000,72.300000,14.100000,1018.400000,0.000000,0.000000,1.000000,17.250000,5.000000,10.000000
max,6527.400000,44.300000,100.000000,39.100000,1047.400000,26.600000,1.000000,1.000000,23.000000,6.000000,12.000000

In [ ]:
print("Total Unique Values In All Columns:")
print(df.nunique().sort_values())

Total Unique Values In All Columns:
holiday              2
weekend              2
season               4
day_of_week          7
month               12
hour                24
precipitation      177
wind_speed         329
temperature        478
pressure           534
humidity           655
demand_MW        18951
datetime         26280
dtype: int64

In [9]:
print("holiday Distribution:")
print(df['holiday'].value_counts().sort_values())

holiday Distribution:
holiday
1      648
0    25632
Name: count, dtype: int64

In [ ]:
print("weekend Distribution:")
print(df['weekend'].value_counts().sort_values())

weekend Distribution:
weekend
1     7536
0    18744
Name: count, dtype: int64

In [11]:
print("season Distribution:")
print(df['season'].value_counts().sort_values())

season Distribution:
season
Winter    6480
Autumn    6552
Summer    6624
Spring    6624
Name: count, dtype: int64